# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ksd < Formula
  desc "ksd` is a tool, whose aim is help you to visualize in text plain your kubernetes secrets, either `yaml` or `json` outputs."
  homepage "https://github.com/mfuentesg/ksd"
  version "1.0.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mfuentesg/ksd/releases/download/v1.0.7/ksd_1.0.7_Darwin_x86_64.tar.gz"
      sha256 "e6067b3127f84d7e11442652bdf247402c45cd91c40a7f63a0d14af75916ee30"

      def install
        bin.install "ksd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mfuentesg/ksd/releases/download/v1.0.7/ksd_1.0.7_Darwin_arm64.tar.gz"
      sha256 "bd54ed80b29493098e99c4c408d0372811fdc270f6c0a5618dfd9dab9bc1afab"

      def install
        bin.install "ksd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mfuentesg/ksd/releases/download/v1.0.7/ksd_1.0.7_Linux_arm64.tar.gz"
      sha256 "69d044b1872f02464bf9cf54f03a477d2624618894cfa850f95da9d228dab182"

      def install
        bin.install "ksd"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mfuentesg/ksd/releases/download/v1.0.7/ksd_1.0.7_Linux_x86_64.tar.gz"
      sha256 "0f696c1d1c46f12b60da63255fec09e7df17346bb1218ba2d002607ba2bd3b15"

      def install
        bin.install "ksd"
      end
    end
  end

  def caveats; <<~EOS
    ksd < kubectl get secret <secret name> <secret file>.<yaml|json>
  EOS
  end

  test do
    ksd version
  end
end
