# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ksd < Formula
  desc "ksd` is a tool, whose aim is help you to visualize in text plain your kubernetes secrets, either `yaml` or `json` outputs."
  homepage "https://github.com/mfuentesg/ksd"
  version "1.0.7"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/mfuentesg/ksd/releases/download/v1.0.7/ksd_1.0.7_Darwin_arm64.tar.gz"
      sha256 "7d994cbb5c70bcf0fd86f095b1400a788e0c226dbb8176bceea02f18400d7945"

      def install
        bin.install "ksd"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mfuentesg/ksd/releases/download/v1.0.7/ksd_1.0.7_Darwin_x86_64.tar.gz"
      sha256 "d1c51ac6cbb09af95ba4190234546d0eaad632e60bfddb1952d62b41ea275009"

      def install
        bin.install "ksd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mfuentesg/ksd/releases/download/v1.0.7/ksd_1.0.7_Linux_x86_64.tar.gz"
      sha256 "41c791ad7014b57c0ceb5913fa381b8e43bff19de6b09e3f6121f088074b57c5"

      def install
        bin.install "ksd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mfuentesg/ksd/releases/download/v1.0.7/ksd_1.0.7_Linux_arm64.tar.gz"
      sha256 "8869b44b8b92bd96c3cf78f1dcb43ad8e9908ece12613cd6060415398659c288"

      def install
        bin.install "ksd"
      end
    end
  end

  def caveats; <<~EOS
    ksd < kubectl get secret <secret name> <secret file>.<yaml|json>
  EOS
  end

  test do
    ksd version
  end
end
