# This file was generated by GoReleaser. DO NOT EDIT.
cask "ksd" do
  version "1.0.12"

  on_macos do
    on_arm do
      sha256 "fb132969a4d5466d00f69e54c42ecb7edbbc81ca0d54947c7103ae11d96bfa51"
      url "https://github.com/mfuentesg/ksd/releases/download/v#{version}/ksd_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c9f82b762521211b94afc55b06dd48df007855d86cf9a9fccf699d71ce3d0569"
      url "https://github.com/mfuentesg/ksd/releases/download/v#{version}/ksd_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "7c5d85cff1ff9b686a0e935493ecf0111cd3ada22d1e8804201c8c4eecb2a81f"
      url "https://github.com/mfuentesg/ksd/releases/download/v#{version}/ksd_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f140d13876310f208e2239e9e6af99ee932739220db85c6f6c6f4ca567ff47db"
      url "https://github.com/mfuentesg/ksd/releases/download/v#{version}/ksd_Linux_x86_64.tar.gz"
    end
  end

  name "ksd"
  desc "Kubernetes Secret Decoder - decode base64-encoded secrets in YAML or JSON format"
  homepage "https://github.com/mfuentesg/ksd"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ksd"

  # No zap stanza required

  caveats <<~EOS
    Usage:
      kubectl get secret <secret-name> -o yaml | ksd
      kubectl get secret <secret-name> -o json | ksd
      ksd < secret.yaml
  EOS
end
