# This file was generated by GoReleaser. DO NOT EDIT.
cask "ksd" do
  version "1.0.13"

  on_macos do
    on_arm do
      sha256 "5285497b856e8ac9162ae986ea767c07bf1cace564b94d5ef31f5f98301f289e"
      url "https://github.com/mfuentesg/ksd/releases/download/v#{version}/ksd_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b88ca12528b75ad3ce640f0e9f9f98e04d7d15d74bab7ef3bb67df27b0db97b6"
      url "https://github.com/mfuentesg/ksd/releases/download/v#{version}/ksd_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "61f859ec91523398669eeb5666fe5bb26176fd8844fc9579cd4a8e70457e3569"
      url "https://github.com/mfuentesg/ksd/releases/download/v#{version}/ksd_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "0ad550e71996878cd345d3c824c89bd5187b296affaac6e5e531d7a0c2e7d43f"
      url "https://github.com/mfuentesg/ksd/releases/download/v#{version}/ksd_Linux_x86_64.tar.gz"
    end
  end

  name "ksd"
  desc "Kubernetes Secret Decoder - decode base64-encoded secrets in YAML or JSON format"
  homepage "https://github.com/mfuentesg/ksd"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ksd"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ksd"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Usage:
      kubectl get secret <secret-name> -o yaml | ksd
      kubectl get secret <secret-name> -o json | ksd
      ksd < secret.yaml
  EOS
end
