# This file was generated by GoReleaser. DO NOT EDIT.
cask "ksd" do
  version "1.0.14"

  on_macos do
    on_arm do
      sha256 "c5b67aa12d662fc376b317d019be63a3626336c364d3a029cf2ff09046482674"
      url "https://github.com/mfuentesg/ksd/releases/download/v#{version}/ksd_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "022faeb68afa19a41c0c102cccddf336a183c53f27a770f692c99ac26e62abbd"
      url "https://github.com/mfuentesg/ksd/releases/download/v#{version}/ksd_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f10f477b9a67b18b02c9481fc60e6cac25a8cd4de70b9d3276708f1337fb2eda"
      url "https://github.com/mfuentesg/ksd/releases/download/v#{version}/ksd_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d459ccf82aa635f9074033abd61afbc42103cd34e52148bd8675b4a09d709480"
      url "https://github.com/mfuentesg/ksd/releases/download/v#{version}/ksd_Linux_x86_64.tar.gz"
    end
  end

  name "ksd"
  desc "Kubernetes Secret Decoder - decode base64-encoded secrets in YAML or JSON format"
  homepage "https://github.com/mfuentesg/ksd"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ksd"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ksd"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Usage:
      kubectl get secret <secret-name> -o yaml | ksd
      kubectl get secret <secret-name> -o json | ksd
      ksd < secret.yaml
  EOS
end
