# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "custom_download_strategy"
class Ksd < Formula
  desc "ksd` is a tool, whose aim is help you to visualize in text plain your kubernetes secrets, either `yaml` or `json` outputs."
  homepage "https://github.com/mfuentesg/ksd"
  version "1.0.6"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/mfuentesg/ksd/releases/download/v1.0.6/ksd_1.0.6_Darwin_x86_64.tar.gz", :using => CurlDownloadStrategy.
    sha256 "9ba25d697c3b049be59f873517ec43c4757a2bdfeed4e2f30ca0902dff21e462"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/mfuentesg/ksd/releases/download/v1.0.6/ksd_1.0.6_Linux_x86_64.tar.gz", :using => CurlDownloadStrategy.
      sha256 "d6631eeef4a30c8fcd5e1dfee81beae4e1d97562b1aaa96d340eaf204cae118a"
    end
  end

  def install
    bin.install "ksd"
  end

  def caveats; <<~EOS
    ksd < kubectl get secret <secret name> <secret file>.<yaml|json>
  EOS
  end

  test do
    ksd version
  end
end
