name: ci
on: [push, pull_request]

jobs:
  install:
    name: Brew install
    runs-on: macos-latest
    steps:
      - name:
        run: |
          brew install mfuentesg/tap/ksd
          ksd version
